### ISSUE TITLE
logging in as my admin user results in an OAuth failure: "An active access token must be used to query information about the current user."

### ISSUE THREAD

**Issue by troygoode** [dailycred/passport-dailycred#2]
Note that logging in as other users works fine (and that I can log into dailycred.com with my admin user, just not my own site.)

Account: "Roll20"
Problematic User ID: 805f336c-f54d-4aba-8830-c1039610ccae

```
Express
500 failed to fetch user profile (status: 400 data: {"error":{"message":"An active access token must be used to query information about the current user.","code":2500,"type":"OAuthException"},"worked":false})
at Strategy.userProfile (/Users/troy/dev/roll20/node_modules/passport-dailycred/lib/passport-dailycred/strategy.js:87:19)
at passBackControl (/Users/troy/dev/roll20/node_modules/passport-dailycred/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:77:9)
at IncomingMessage.exports.OAuth2._request.request.on.callbackCalled (/Users/troy/dev/roll20/node_modules/passport-dailycred/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:94:7)
at IncomingMessage.EventEmitter.emit (events.js:115:20)
at IncomingMessage._emitEnd (http.js:366:10)
at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
at CleartextStream.CryptoStream._push (tls.js:495:27)
at SecurePair.cycle (tls.js:849:20)
at EncryptedStream.CryptoStream.write (tls.js:230:13)
```

**Comment by hstove** [comment]
Hey there -

Nice catch with this bug. I'm mostly sure that this bug is related to our backend, and not this node.js module, because of the fact that it's working for your other users. I've filed a bug in our internal repo and will be looking into this.

Again, thanks for the report! 

Hank
